name: timetracker_api
description: A Dart package that defines the core API for time-tracking operations.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  very_good_analysis: ^6.0.0

flutter:
  generate: true