name: timetracker
description: Request Finance Time Tracker is a free, open-source time tracking tool designed for freelancers, agencies, and businesses. It's easy to use and supports creating invoices in cryptocurrency.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  blobs: ^2.0.0

  wave: ^0.2.2  
  uuid: ^4.3.3
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6

  reown_appkit: ^1.2.0

  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter

  timetracker_api:
    path: packages/timetracker_api
  local_storage_timetracker_api:
    path: packages/local_storage_timetracker_api
  timetracker_repository:
    path: packages/timetracker_repository
  draggable_carousel_slider:
    path: packages/draggable_carousel_slider

  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/icon.png
    - assets/images/icon_white.png
    - assets/images/profile-picture.png
    - assets/images/tokens/eth.png
    - assets/images/tokens/btc.png
    - assets/images/tokens/bnb.png
    - assets/images/landing/landing_1.png
    - assets/images/landing/landing_2.png
    - assets/images/landing/landing_3.png

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
