name: local_storage_timetracker_api
description: A Dart package implementing a local storage-based API for the time tracker. 
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies: 
  sqflite: ^2.4.1
  timetracker_api:
    path: ../timetracker_api


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
