name: network_timetracker_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies: 
  convert: ^3.1.2
  crypto: ^3.0.6
  http: ^1.2.2
  json_sorter: ^1.0.0
  pointycastle: ^3.9.1
  rxdart: ^0.27.5
  timetracker_api:
    path: ../timetracker_api
  meta: ^1.7.0


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
