name: timetracker_repository
description: A Dart package designed to serve as the central repository layer for managing time-tracking data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
